#### 1. Import the numpy package under the name `np` (★☆☆)

In [5]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
np.__version__

'1.23.1'

#### 3. Create a null vector of size 10 (★☆☆)

In [14]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)


In [15]:
a.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [17]:
np.add?


#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
a=np.array([0,0,0,0,1,0,0,0,0,0])

In [24]:
b=np.zeros(10)
b[4] = 1
b

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [25]:
b = np.random.randint(10,49,10)

In [26]:
b

array([21, 10, 42, 24, 23, 44, 13, 32, 37, 40])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [32]:
c = b[::-1]
c

array([40, 37, 32, 13, 44, 23, 24, 42, 10, 21])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [34]:
vec = np.random.randint(0,8,(3,3))
vec

array([[1, 0, 5],
       [4, 4, 7],
       [6, 3, 2]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [35]:
vec = np.array([1,2,0,0,4,0])
vec

array([1, 2, 0, 0, 4, 0])

In [38]:
inde= 0
for x in vec:
    if x== 0:
        print(inde)
    inde=inde+1

2
3
5


#### 11. Create a 3x3 identity matrix (★☆☆)

In [42]:
vec = np.full((3,3),1)
vec

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [47]:
vec = np.random.randint(0,50,size=(3,3,3))
vec

array([[[42, 24, 23],
        [ 4, 33, 32],
        [11,  2,  5]],

       [[47, 31, 18],
        [49, 17, 13],
        [12, 14, 33]],

       [[32, 40, 47],
        [41, 40, 12],
        [17,  7, 27]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)


In [57]:
vec = np.random.randint(1,50,size=(10,10))
print(vec)
print(vec.min())
print(vec.max())

[[37  7 42 42 18 32 44 23 22 40]
 [29  4 43 36 28 16 34  2 44 25]
 [48 49 43 18 39  1 25 25 44 44]
 [31 18 32 37 11  8 14 46 31 11]
 [ 1 30 16  6 49 46 19 44  8 32]
 [15 20 37 18 33 14 31 15  9 46]
 [48 22 41 45 29 27  6 40 22 21]
 [13 46 46 20 38 22  9 18 25 38]
 [27 17 13  8 40 10 23 38 18 25]
 [47 10  7  5 18 14  4 22 16 39]]
1
49


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)


In [59]:
vec = np.random.randint(1,50,30)
vec
vec.mean()

29.533333333333335

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [67]:
vec = np.full((4,4),1)
vec

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [68]:
vec[1:-1,1:-1]=0
vec

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)


In [70]:
vec = np.random.randint(1,50,(5,5))
vec

array([[48,  8,  9, 17, 13],
       [11, 44, 37,  8, 41],
       [ 1, 24,  6,  7, 25],
       [34, 27, 10, 49, 15],
       [ 5, 39, 21,  5, 41]])

In [73]:
np.pad(vec,1)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0, 48,  8,  9, 17, 13,  0],
       [ 0, 11, 44, 37,  8, 41,  0],
       [ 0,  1, 24,  6,  7, 25,  0],
       [ 0, 34, 27, 10, 49, 15,  0],
       [ 0,  5, 39, 21,  5, 41,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [74]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False